/**
 * Canonical AuditLog action names. Every important create/update/delete/
 * status-change must write an AuditLog (see `src/lib/audit.ts`) using one of
 * these constants as the `action`.
 */
export const AUDIT_ACTIONS = {
  // Users & staff
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DISABLED: "USER_DISABLED",
  USER_ENABLED: "USER_ENABLED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_PASSWORD_RESET_REQUESTED: "USER_PASSWORD_RESET_REQUESTED",

  // Customers
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  CUSTOMER_MERGED: "CUSTOMER_MERGED",

  // Parcels
  PARCEL_CREATED: "PARCEL_CREATED",
  PARCEL_UPDATED: "PARCEL_UPDATED",
  PARCEL_STATUS_CHANGED: "PARCEL_STATUS_CHANGED",
  PARCEL_PRICE_UPDATED: "PARCEL_PRICE_UPDATED",
  PARCEL_OWNER_UPDATED: "PARCEL_OWNER_UPDATED",
  PARCEL_MARKED_UNIDENTIFIED: "PARCEL_MARKED_UNIDENTIFIED",
  PARCEL_LINKED_TO_CUSTOMER: "PARCEL_LINKED_TO_CUSTOMER",
  PARCEL_DELETED: "PARCEL_DELETED",
  PARCEL_RESTORED: "PARCEL_RESTORED",

  // Unidentified cargo / ownership claims
  OWNERSHIP_CLAIM_CREATED: "OWNERSHIP_CLAIM_CREATED",
  OWNERSHIP_CLAIM_APPROVED: "OWNERSHIP_CLAIM_APPROVED",
  OWNERSHIP_CLAIM_REJECTED: "OWNERSHIP_CLAIM_REJECTED",
  UNIDENTIFIED_CARGO_UPDATED: "UNIDENTIFIED_CARGO_UPDATED",
  UNIDENTIFIED_CARGO_RESOLVED: "UNIDENTIFIED_CARGO_RESOLVED",

  // Shipment batches
  BATCH_CREATED: "BATCH_CREATED",
  BATCH_UPDATED: "BATCH_UPDATED",
  BATCH_ITEM_ADDED: "BATCH_ITEM_ADDED",
  BATCH_ITEM_REMOVED: "BATCH_ITEM_REMOVED",
  BATCH_STATUS_CHANGED: "BATCH_STATUS_CHANGED",
  MANIFEST_VIEWED: "MANIFEST_VIEWED",
  MANIFEST_EXPORTED: "MANIFEST_EXPORTED",
  BATCH_CANCELLED: "BATCH_CANCELLED",
  BATCH_REOPENED: "BATCH_REOPENED",

  // Link orders
  LINK_ORDER_CREATED: "LINK_ORDER_CREATED",
  LINK_ORDER_UPDATED: "LINK_ORDER_UPDATED",
  LINK_ORDER_STATUS_CHANGED: "LINK_ORDER_STATUS_CHANGED",
  LINK_ORDER_TRACK_CODE_ADDED: "LINK_ORDER_TRACK_CODE_ADDED",
  LINK_ORDER_LINKED_TO_PARCEL: "LINK_ORDER_LINKED_TO_PARCEL",
  LINK_ORDER_CANCELLED: "LINK_ORDER_CANCELLED",

  // Deliveries
  DELIVERY_ASSIGNED: "DELIVERY_ASSIGNED",
  DELIVERY_REASSIGNED: "DELIVERY_REASSIGNED",
  DELIVERY_STATUS_CHANGED: "DELIVERY_STATUS_CHANGED",
  DELIVERY_FEE_UPDATED: "DELIVERY_FEE_UPDATED",
  DELIVERY_CANCELLED: "DELIVERY_CANCELLED",

  // Tariffs
  TARIFF_CREATED: "TARIFF_CREATED",
  TARIFF_UPDATED: "TARIFF_UPDATED",
  TARIFF_ACTIVATED: "TARIFF_ACTIVATED",
  TARIFF_DEACTIVATED: "TARIFF_DEACTIVATED",
  TARIFF_DELETED: "TARIFF_DELETED",

  // Banners & content
  BANNER_CREATED: "BANNER_CREATED",
  BANNER_UPDATED: "BANNER_UPDATED",
  BANNER_ACTIVATED: "BANNER_ACTIVATED",
  BANNER_DEACTIVATED: "BANNER_DEACTIVATED",
  CONTENT_UPDATED: "CONTENT_UPDATED",

  // Notifications
  NOTIFICATION_SENT: "NOTIFICATION_SENT",
  NOTIFICATION_FAILED: "NOTIFICATION_FAILED",
  NOTIFICATION_RETRIED: "NOTIFICATION_RETRIED",
  BULK_NOTIFICATION_SENT: "BULK_NOTIFICATION_SENT",
  NOTIFICATION_SETTINGS_UPDATED: "NOTIFICATION_SETTINGS_UPDATED",

  // Reports
  REPORT_VIEWED: "REPORT_VIEWED",
  REPORT_EXPORTED: "REPORT_EXPORTED",

  // System settings
  SYSTEM_SETTING_UPDATED: "SYSTEM_SETTING_UPDATED",

  // Warehouses
  WAREHOUSE_CREATED: "WAREHOUSE_CREATED",
  WAREHOUSE_UPDATED: "WAREHOUSE_UPDATED",
  WAREHOUSE_DELETED: "WAREHOUSE_DELETED",

  // Branches
  BRANCH_CREATED: "BRANCH_CREATED",
  BRANCH_UPDATED: "BRANCH_UPDATED",
  BRANCH_DELETED: "BRANCH_DELETED",

  // FAQ
  FAQ_CREATED: "FAQ_CREATED",
  FAQ_UPDATED: "FAQ_UPDATED",
  FAQ_DELETED: "FAQ_DELETED",

  // Testimonials
  TESTIMONIAL_CREATED: "TESTIMONIAL_CREATED",
  TESTIMONIAL_UPDATED: "TESTIMONIAL_UPDATED",
  TESTIMONIAL_DELETED: "TESTIMONIAL_DELETED",

  // Auth (session lifecycle)
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
